set_property SRC_FILE_INFO {cfile:D:/fpga/kitap1b/1_not_gate/1_not_gate.srcs/constrs_1/imports/kitap1b/Cmod-A7-Master.xdc rfile:../../../1_not_gate.srcs/constrs_1/imports/kitap1b/Cmod-A7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A17   IOSTANDARD LVCMOS33 } [get_ports { led }]; #IO_L12N_T1_MRCC_16 Sch=led[1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { btn }]; #IO_L19P_T3_16 Sch=btn[1]
